blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('published/<int:pk>/', toggle_activity, name='toggle_activity')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Blog(models.Model):
    title = models.CharField(
        max_length=200, verbose_name='Заголовок', help_text="Введите заголовок"
    )
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='Текст поста', help_text='Введите содержимое поста')
    photo = models.ImageField(upload_to="blog/", verbose_name='фото', help_text='Вставьте фото', **NULLABLE)
    created_at = models.DateField(**NULLABLE, auto_now_add=True)
    is_published = models.BooleanField(default=True)
    views_counter = models.PositiveIntegerField(
        default=0,
        verbose_name='Счетчик просмотров'
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'

blog/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog


class BlogListView(ListView):
    model = Blog

    # def get_queryset(self, *args, **kwargs):
    #     queryset = super().get_queryset()
    #     queryset = queryset.filter(is_published=True)
    #     return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'photo')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()
            return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'photo', 'is_published')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()
            return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:detail', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')


def toggle_activity(request, pk):
    post_item = get_object_or_404(Blog, pk=pk)
    if post_item.is_published:
        post_item.is_published = False
    else:
        post_item.is_published= True

    post_item.save()
    return redirect(reverse('blog:list'))

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text "><center>Действитильно ли вы хотите удалить пост {{ object }}</center></p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <button type="submit" class="btn btn-primary">
                      Удалить
                    </button>
                    <p>
                        <a class="btn btn-primary" href="{% url 'blog:list' %}" role="button">Отмена</a>
                    </p>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    {% if object.photo %}
                        <img src="{{ object.photo | media_filter }}">
                    {% endif %}
                    <div class="card-body">
                        <p class="card-text">{{ object.title}} ({{ object.slug }})</p>
                        <p class="card-text">{{ object.content }}</p>

                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'blog:list' %}"
                                   role="button">Назад</a>
                            </div>
                            <small class="text-body-secondary"></small>
                        </div>
                    </div>
                    <div class="card-footer">
                        Просмотры {{ object.views_counter }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'blog:create' %}"> Написать пост</a>
    </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{ object.photo | media_filter }}">
                    <div class="card-body">
                        <p class="card-text ">
                            {% if object.is_published %}
                        <p style="color: green;">{{ object|title }}</p>
                        {% else %}
                        <p style="color: red;">{{ object|title }}</p>
                        {% endif %}
                        </p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'blog:detail' object.pk %}"
                                   role="button">Детали</a>
                                <a class="btn btn-primary" href="{% url 'blog:update' object.pk %}"
                                   role="button">Изменить</a>
                                <a class="btn btn-primary" href="{% url 'blog:delete' object.pk %}"
                                   role="button">Удалить</a>
                            </div>
                            {% if object.is_published %}
                            <a href="{% url 'blog:toggle_activity' object.pk %}">Cнять</a>
                            {% else %}
                            <a href="{% url 'blog:toggle_activity' object.pk %}">Выставить</a>
                            {% endif %}
                        </div>

                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}